### ISSUE TITLE
[Bug]: Design token themed folder cannot be published out of the box.

### ISSUE THREAD

**Issue by jwwheeleriv** [cloudscape-design/theming-core#35]
### Package version

^3.0.74

### node-versions

16.13.2

### npm-versions

8.1.2

### Description

In the documentation (https://cloudscape.design/foundation/visual-foundation/theming/) at the bottom it states the following:

After building the themed version of the artifacts, you will have two options:
1. Publish the /components and /design-tokens folders as new packages (recommended)
2. Use the output as a local NPM dependency: extend the dependencies section in your package.json file by "@cloudscape-design/components-themed": "file:<path to output>/components and "@cloudscape-design/design-tokens-themed": "file:<path to output>/design-tokens". Run the npm install command afterwards.

Regardless of either option you cannot simply publish the packages I think there is a gap in the documentation that needs to explicitly state there is more work required to publish or use the packages.  

Ultimately, the design tokens are my focus here and there is no package.json file created in the design-tokens folder to even publish a package once you have run the buildThemedComponents function.  In addition everything is named visual-refresh.xxx.  By convention it would be my recommendation to name the .d.ts, .scss and .js files to index.xxx and follow the same convention you do for the standard design-tokens library.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/theming-core/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/theming-core/issues) for duplicate problems

**Comment by johannes-weber** [comment]
Hi @jwwheeleriv, thanks for reporting! I was able to reproduce the issue locally. We'll investigate and keep this issue updated about findings.
